// Compiles story/oompa.ink into js/story.js (a plain script, so the game
// runs from file:// and on any static host with no fetch).
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import * as ink from 'inkjs/full';

const root = new URL('..', import.meta.url);
const source = readFileSync(new URL('story/oompa.ink', root), 'utf8');
const compiler = new ink.Compiler(source);
let story;
try {
  story = compiler.Compile();
} catch (e) {
  // fall through: errors are reported below
}
for (const w of compiler.warnings) console.warn('ink warning:', w);
if (compiler.errors.length || !story) {
  for (const e of compiler.errors) console.error('ink error:', e);
  process.exit(1);
}
const json = story.ToJson();
writeFileSync(new URL('js/story.js', root), `// Generated by scripts/build.mjs from story/oompa.ink. Do not edit.\nwindow.OOMPA_STORY = ${json};\n`);
console.log(`story compiled: ${(json.length / 1024).toFixed(1)} KB`);
if (compiler.warnings.length) process.exit(1);
